### PR TITLE
Enable the search

### PR DESCRIPTION
**Pull request by lpugin**
@HirschSt just close the PR if you don't want the search on the site. It should work out-of-the-box, though

### CODE REVIEW

**Comment by HirschSt** [comment]
@lpugin I really like the websearch function, but at de-stage.rism.info the query (eg "Berlin") returns "Some of our pages have moved." etc. Anything to adjust?

**Comment by ahankinson** [comment]
@HirschSt you probably need to also add a `search.en.md` file, as in the rism.info website:

https://github.com/rism-digital/rism.info/blob/staging/search.en.md

**Comment by HirschSt** [comment]
@ahankinson thanks, good point :+1: I will give this a try next week

**Comment by lpugin** [comment]
Yes, @ahankinson is right. Sorry about that.

**Pull request merged**
